"""add weather tables

Revision ID: 222c78fa18ab
Revises: 
Create Date: 2023-01-06 15:56:15.469799

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "222c78fa18ab"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agg_weather_report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("station", sa.String(), nullable=False),
        sa.Column("measure_year", sa.Integer(), nullable=False),
        sa.Column("max_temperature", sa.Integer(), nullable=True),
        sa.Column("min_temperature", sa.Integer(), nullable=True),
        sa.Column("total_precipitation_cm", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weather",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("station", sa.String(), nullable=False),
        sa.Column("measure_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("max_temperature", sa.Integer(), nullable=True),
        sa.Column("min_temperature", sa.Integer(), nullable=True),
        sa.Column("precipitation_mm", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # adding unique constraint for column
    op.create_unique_constraint(
        "uniq_weather_station_date", "weather", ["station", "measure_date"]
    )
    op.create_index("weather_station", "weather", ["station"])
    op.create_index("weather_date", "weather", ["measure_date"])

    op.create_unique_constraint(
        "uniq_agg_weather_report_station_date",
        "agg_weather_report",
        ["station", "measure_year"],
    )
    op.create_index("agg_weather_report_station", "agg_weather_report", ["station"])
    op.create_index("agg_weather_report_year", "agg_weather_report", ["measure_year"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather")
    op.drop_table("agg_weather_report")
    # ### end Alembic commands ###

    # removing unique constraints
    op.drop_constraint("uniq_weather_station_date")
    op.drop_index("weather_station")
    op.drop_index("weather_date")

    op.drop_constraint("uniq_agg_weather_report_station_date")
    op.drop_index("agg_weather_report_station")
    op.drop_index("agg_weather_report_year")
